packages:
  - "phases"
  - "web/react_app"
  # - "cli/terminal_app"
  # - "api"
  # - "game/*"
  # - "db"
  # - "config"
  # - "data"
  # - "utils"
  # - "scripts"
  # - "types"
  # - "docs"
  # - "examples/*"
  # - "packages/*"
  # - "tools/*"
  # - "workbench/*"
  # - "services/*"
  # - "libs/*"
  # - "components/*"
  # - "hooks/*"
  # - "contexts/*"
  # - "providers/*"
  # - "middleware/*"
  # - "plugins/*"
